### ISSUE TITLE
"flag redefined: ginkgo.seed" occurs when run test under directory tests

### ISSUE THREAD

**Issue by gouyang** [kubevirt/kubevirt-ansible#343]
I can't get rid of this error when trying to run test directory tests, it just won't run if import `kubevirt.io/kubevirt/tests` in any file. 

```
# pwd
/root/tests
# ls
tests_suite_test.go
# cat tests_suite_test.go 
package tests_test

import (
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"

	"testing"
	
	"kubevirt.io/kubevirt/tests"
)

func TestTests(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Tests Suite")
}

var _ = BeforeSuite(func() {
	tests.BeforeTestSuitSetup()
})

var _ = AfterSuite(func() {
	tests.AfterTestSuitCleanup()
})
# go test .
/tmp/go-build827926168/_/root/tests/_test/tests.test flag redefined: ginkgo.seed
panic: /tmp/go-build827926168/_/root/tests/_test/tests.test flag redefined: ginkgo.seed

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc420092000, 0x1c1eda0, 0x1deb360, 0xc42007f460, 0xb, 0x13d287d, 0x2a)
	/usr/lib/golang/src/flag/flag.go:793 +0x5e1
flag.(*FlagSet).Int64Var(0xc420092000, 0x1deb360, 0xc42007f460, 0xb, 0x5b6307a2, 0x13d287d, 0x2a)
	/usr/lib/golang/src/flag/flag.go:618 +0x71
kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/config.Flags(0xc420092000, 0xc42015be18, 0x7, 0x1)
	/root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/config/config.go:68 +0x148
kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo.init.0()
	/root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:55 +0x59
kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo.init()
	<autogenerated>:1 +0xa2
kubevirt.io/kubevirt/tests.init()
	<autogenerated>:1 +0xa2
_/root/tests_test.init()
	<autogenerated>:1 +0x5a
main.init()
	<autogenerated>:1 +0x53
FAIL	_/root/tests	0.022s
```

**Comment by gouyang** [comment]
I doubt it's an issue in `kubevirt/tests` because it calls flag.Parse()` more than once.

**Comment by shiywang** [comment]
there're two places you need to change to make your code being executed by CI
`hack/common.sh` `hack/run-tests.sh`

**Comment by gouyang** [comment]
Don't see this problem if run tests in `kubevirt.io/kubevirt-ansible/tests`.

**Comment by navarrothiago** [comment]
In my case, I noticed that there were two ginkgo module (v1 and v2) defined inside my go.mod. So, two init function for each ginkgo package have been called. For some reason, I messed with these files. After leaving just one version, it worked.

**Comment by jackstine** [comment]
fixed this problem by changing the ginkgo go lang import from `"github.com/onsi/ginkgo"` to `"github.com/onsi/ginkgo/v2"`
